// This file contains the hardcoded Supabase credentials.
export const SUPABASE_URL = 'https://pqsppjjmlwemkxyehuqz.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxc3BwamptbHdlbWt4eWVodXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxMTE5NTgsImV4cCI6MjA4NTY4Nzk1OH0.nZ8wnOAzMaV6wgxkj0C8F5zkckh2QwOwt1t8A-PEkr8';
